import { Check, CheckCircle2, Download, Mail, Search } from 'lucide-react'
import jsPDF from 'jspdf'
import { Link, Navigate, useParams } from 'react-router-dom'
import { Layout, StatusBadge } from '../components'
import { activeProcesses } from '../data'
import { formatDate, getRequests } from '../store'

export default function Confirmation() {
  const { serial } = useParams(); const request = getRequests().find((item) => item.serialCode === serial)
  if (!request) return <Navigate to="/request" />
  const download = () => { const pdf = new jsPDF(); pdf.setFillColor(11, 59, 54); pdf.rect(0, 0, 210, 38, 'F'); pdf.setTextColor(255, 255, 255); pdf.setFontSize(24); pdf.text('EasePH', 18, 23); pdf.setTextColor(25, 35, 34); pdf.setFontSize(18); pdf.text('Government Service Request Receipt', 18, 55); pdf.setFontSize(10); pdf.setTextColor(90, 100, 98); pdf.text('This receipt is for demonstration purposes only.', 18, 63); const entries = [['Serial code', request.serialCode], ['Process', request.processName], ['Business', request.businessName], ['Applicant', request.applicantName], ['Submitted', formatDate(request.dateSubmitted)], ['Assigned agency', request.agency], ['Current status', request.status], ['Estimated time', activeProcesses[request.processId].estimate]]; let y = 82; entries.forEach(([label, value]) => { pdf.setFont('helvetica', 'bold'); pdf.setTextColor(80, 90, 88); pdf.text(label.toUpperCase(), 18, y); pdf.setFont('helvetica', 'normal'); pdf.setTextColor(20, 32, 30); pdf.text(value, 18, y + 7, { maxWidth: 175 }); y += value.length > 70 ? 27 : 20 }); pdf.setDrawColor(210, 220, 217); pdf.line(18, y, 192, y); pdf.setTextColor(60, 74, 71); pdf.text(`Check your request anytime at EasePH using ${request.serialCode}.`, 18, y + 12); pdf.save(`${request.serialCode}-receipt.pdf`) }
  return <Layout><main className="confirmation-page"><div className="container confirmation-wrap"><div className="success-icon"><Check /></div><span className="eyebrow">Request submitted</span><h1>Your request is on its way.</h1><p>Keep your serial code safe. You will use it to track progress.</p><div className="serial-card"><span>YOUR SERIAL CODE</span><strong>{request.serialCode}</strong><small>Submitted {formatDate(request.dateSubmitted)}</small></div><div className="confirmation-card"><div className="confirmation-title"><div><h2>{request.processName}</h2><p>{request.businessName}</p></div><StatusBadge status={request.status} /></div><dl><div><dt>Assigned agency</dt><dd>{request.agency}</dd></div><div><dt>Estimated processing</dt><dd>{activeProcesses[request.processId].estimate}</dd></div><div><dt>Applicant</dt><dd>{request.applicantName}</dd></div><div><dt>Date submitted</dt><dd>{formatDate(request.dateSubmitted)}</dd></div></dl><div className="email-notice"><Mail /><span><b>Receipt email simulated</b><small>A copy of your receipt has been sent to {request.email}.</small></span></div></div><div className="confirmation-actions"><button className="button button-primary" onClick={download}><Download /> Download receipt</button><Link className="button button-subtle" to={`/status?serial=${request.serialCode}`}><Search /> Check status</Link></div><p className="next-note"><CheckCircle2 /> You may close this page. Your request is saved in this browser.</p></div></main></Layout>
}
